#!/bin/bash
for i in 5 6 11 15 18 ; do
 for j in 5 6 11 15 18 ; do
  if [ $(echo "$i<$j" | bc -l ) == 1 ] ; then 
  echo $i $j
  fi
 done
done
for i in 7 8 9 12 13 14 16 17 19 20 21 22 23 24 ; do
 for j in 7 8 9 12 13 14 16 17 19 20 21 22 23 24 ; do
  if [ $(echo "$i<$j" | bc -l ) == 1 ] ; then
  echo $i $j
  fi
 done
done
